== v1.6.1

*Release Number:* v1.6.1

*Release Date:* 29th Jul, 2025

=== Overview

We’re excited to announce the upcoming release of
https://github.com/mosip/esignet/tree/v1.6.1[*eSignet v1.6.1*], a major
update packed with new features, improved configurability, and enhanced
security. This version brings greater flexibility for Relying Parties
(RPs) to customize login experiences, a revamped UI, and significant
improvements to deployment processes.

++{++% hint style="`success`" %} *Version Note:* 

*eSignet v1.6.1* is a patch release over the originally planned
*v1.6.0*, addressing critical deployment-related bug fixes. It is the
latest official version following *eSignet v1.5.1*. ++{++% endhint %}

=== Major Highlights

==== New Features

* https://docs.esignet.io/esignet-authentication/develop/configuration/login-id-configuration-in-esignet[*Prefix
& Postfix support for Choice of Login ID*] +
Configure login ID types (Email, Phone, VID, etc.) as per relying party
(RP) needs. Comes with a revamped, more intuitive UI.
* https://github.com/mosip/esignet/blob/v1.6.1/docs/esignet-openapi.yaml#L36[*Customizable
Client Configuration*] +
Enhanced client management endpoint with additional options for better
customization and control of eSignet’s behavior.
* https://docs.esignet.io/esignet-authentication/develop/configuration/purpose-based-ui-rendering-in-esignet[*Purpose-Based
eSignet UI*] +
UI dynamically adapts titles and tile subtitles based on the context and
purpose of the service, providing a more relevant user experience.

==== Enhancements

* *JTI Mandatory in Client Assertion* +
JTI is now a required parameter in the client assertion JWT in token
endpoint for improved security.
+
⚠️ *Breaking Change*: Existing relying parties (RPs) must include the
`jti` claim to share consented claims successfully.
* *Unique nonce for each transaction:* nonce query parameter in the
https://docs.esignet.io/esignet-authentication/develop/integration/relying-party/development-and-integration-with-esignet#get-authorize[authorize
url] should be unique for each transaction.
+
⚠️ *Breaking Change*: If duplicate nonce is found “invalid++_++request“
error is thrown.
* *Updated Vulnerable Libraries* +
Security has been bolstered by updating dependencies and patching known
vulnerabilities.
* https://github.com/mosip/esignet/blob/v1.6.1/deploy/README.md[*Improved
Deployment Scripts*] +
Upgraded installation scripts provide a smoother experience for new
deployments of eSignet.

=== Features Released

[width="100%",cols="39%,61%",options="header",]
|===
|Feature |Jira
|Prefix & Postfix support for Choice of Login ID
|https://mosip.atlassian.net/browse/ES-1665[ES-1665]

|Customizable Client Configuration
|https://mosip.atlassian.net/browse/ES-1655[ES-1655]

|Purpose-Based eSignet UI
|https://mosip.atlassian.net/browse/ES-216[ES-216]

|Deployment Script Update
|https://mosip.atlassian.net/browse/MOSIP-40529[MOSIP-40529]
|===

=== Security Enhancements

*Library Upgrades for Vulnerability Fixes:*

Dependencies in eSignet service have been upgraded to fix known
vulnerabilities.

=== Bug Fixes

Several known issues from the previous release have been addressed to
improve platform stability and performance.

Please refer to the
https://mosip.atlassian.net/issues/?filter=-4&jql=%22Release%20Number%5BLabels%5D%22%20%3D%20eSignet_v1.6.1%20and%20issuetype%20%3D%20Bug%20and%20status%20IN%20%28Closed%29[link
here] for the complete list of resolved issues.

=== Key Known Issues

[width="100%",cols="41%,59%",options="header",]
|===
|Jira Issue |Summary
|https://mosip.atlassian.net/browse/ES-2317[ES-2317] |Verified Consented
claims are not returned in userinfo response in MOSIP IDA

|https://mosip.atlassian.net/browse/ES-2359[ES-2359] |Getting
`invalid++_++request` when the `additional++_++config` is added for the
client
|===

Please refer to
https://mosip.atlassian.net/issues/?filter=-4&jql=labels%20%3D%20known_issue_eSignet_1.6.1[link
here] for the full list of known issues.

=== Repositories Released

[width="100%",cols="24%,76%",options="header",]
|===
|Repository |Tags
|esignet |https://github.com/mosip/esignet/tree/v1.6.1[v1.6.1]

|esignet-signup
|https://github.com/mosip/esignet-signup/tree/v1.2.1[v1.2.1]

|esignet-mock-services
|https://github.com/mosip/esignet-mock-services/tree/v0.11.1[v0.11.1]

|esignet-plugins
|https://github.com/mosip/esignet-plugins/tree/v1.3.2[v1.3.2]
|===

=== Compatibility Matrix

*eSignet with MOSIP compatibility matrix*

[width="100%",cols="19%,81%",options="header",]
|===
|Module/Repo |Compatible Version
|ID Authentication
|https://github.com/mosip/id-authentication/tree/v1.2.1.0[1.2.1.0]

|PMS
|https://github.com/mosip/partner-management-services/tree/v1.2.2.1[1.2.2.1]
|===

*eSignet with Sunbird compatibility matrix*

[width="100%",cols="13%,87%",options="header",]
|===
|Module/Repo |Compatible Version
|Sunbird
|https://github.com/Sunbird-RC/sunbird-rc-core/tree/v2.0.0-rc3[v2.0.0-rc3]
|===

*Signup with MOSIP compatibility matrix*

[width="100%",cols="15%,85%",options="header",]
|===
|Module/Repo |Compatible Version
|ID Repository
|https://github.com/mosip/id-repository/tree/v1.2.2.1[1.2.2.1]

|Keymanager |https://github.com/mosip/keymanager/tree/v1.2.1.0[1.2.1.0]

|PMS
|https://github.com/mosip/partner-management-services/tree/v1.2.2.1[1.2.2.1]
|===

=== Config Changes

==== eSignet

[arabic]
. Added the following configurations to provide a structured and
flexible approach to supporting multiple login ID types:

`mosip.esignet.ui.config.login-id.options=`

`mosip.esignet.ui.config.login-id.options=`

Allows customization for each ID type, including options such as:

* *Prefixes* (e.g., country codes for mobile numbers)
* *Associated icons* for improved UI experience
* *Validation rules*, such as regular expressions or length constraints

[arabic, start=2]
. Property to configure additional config schema

`mosip.esignet.additional-config.schema.url`

Please
https://github.com/mosip/esignet/blob/v1.6.1/esignet-service/src/main/resources/application-default.properties[refer
here] for details.

=== eSignet Mock Services

[arabic]
. Property to configure the url to fetch the schema of additional config

`mosip.mock.ui-spec.schema.url`

Please
https://github.com/mosip/esignet-mock-services/blob/v0.11.1/mock-identity-system/src/main/resources/application-default.properties[refer
here] for details.

=== Database Changes

==== eSignet

[arabic]
. *New column:* `additional++_++config` of type `jsonb` added to the
`client++_++detail` table for storing flexible JSON configuration data.
. *Increased length of `name` column* in the `client++_++detail` table
to *600 characters* to support longer client names.

Please
https://github.com/mosip/esignet/blob/release-1.6.x/db_upgrade_script/mosip_esignet/sql/1.5.1_to_1.6.0_upgrade.sql[refer
here] for details.

==== eSignet Mock Services

[arabic]
. Modified the `identity++_++json` column in the `client++_++detail`
table to use `VARCHAR` *without a length limit*, allowing for
variable-length string data of unlimited size.

Please
https://github.com/mosip/esignet-mock-services/blob/release-0.11.x/db_upgrade_script/mosip_mockidentitysystem/sql/0.10.1_to_0.11.0_upgrade.sql[refer
here] for details.

=== Documentation

*API Documentation*

* https://github.com/mosip/esignet/blob/v1.6.1/docs/esignet-openapi.yaml[*eSignet
API (v1.6.1)*]
* https://github.com/mosip/esignet-signup/blob/v1.2.1/docs/esignet-signup-openapi.yaml[*Signup
API (v1.2.1)*]

*Integration Guides*

* https://docs.esignet.io/esignet-authentication/develop/integration[*eSignet
Integration Guide*]
* https://docs.esignet.io/esignet-signup/develop/integration-guide-signup-portal[*Signup
Integration Guide*]

*End User Guides*

* https://docs.esignet.io/esignet-authentication/test/end-user-guide[*eSignet
End User Guide*]
* https://docs.esignet.io/esignet-signup/test/end-user-guide[*Signup End
User Guide*]

link:test-report.md[*QA Report*]
