== Test Report

=== Testing Scope

The scope of testing is to verify fitment to the specification from the
perspective of

* Functionality
* Deployability
* Configurability
* Customizability

Verification is performed not only from the end user perspective but
also from the System Integrator (SI) point of view. Hence, the
Configurability and Extensibility of the software is also assessed. This
ensures the readiness of software for use in multiple countries. Since
MOSIP is an “API First” product platform, Verification scope required
comprehensive automation testing for all the MOSIP APIs. An automation
Test Rig is created for the same.

=== Test Approach

Persona based approach has been adopted to perform the IV&V, by
simulating test scenarios that resemble a real-time implementation.

A Persona is a fictional character/user profile created to represent a
user type that might use a product/or a service in a similar way.
Persona based testing is a software testing technique that puts software
testers in the customer’s shoes, assesses their needs from the software
and thereby determines use cases/scenarios that the customers will
execute. The persona needs may be addressed through any of the
following.

* Functionality
* Deployability
* Configurability
* Customizability

The verification methods may differ based on how the need was addressed.

For regression check, “MOSIP Test Rig” - an automation testing suite -
which is indigenously designed and developed for supporting persona
based testing. MOSIP Test Rig covers the end to end test execution and
reporting. The end to end functional test scenarios are written starting
from pre-registration, to creation of packet in registration center,
processing the packet through the registration processor, generating UIN
and authenticating identity using IDA through various permutation and
combinations of cases being covered. MOSIP Test Rig will be an open
source artifact which can also be enhanced and used by countries to
validate the SI deliveries before going live. Persona classes include
both negative and positive personas. Negative persona classes include
users like Bribed Registration Office, Malicious Insider etc. The needs
of positive persona classes must be met, whereas the needs of negative
persona classes must be effectively restricted by the software.

=== Verified configuration

Verification is performed on various configurations as mentioned below

Default configuration -

* eSignet with 7 languages
(English/Khmer/Hindi/Kannada/Tamil/Arabic/French)
* Signup with 2 languages (Khmer/English)

===== Main feature tested:

* Signup Portal with mock ID
* Login with Password with mock ID
* Forgot Password with mock ID
* Login with OTP with mock ID
* Login with biometrics with mock ID
* Login with KBI with mock ID
* Identity verification process (L2 flow) with mock ID
* Signup Portal with MOSIP IDA
* Login with Password with MOSIP IDA
* Forgot Password with MOSIP IDA
* Login with OTP with MOSIP IDA
* Login with biometrics MOSIP IDA
* Sunbird Plugin with MOSIP IDA
* Critical and Blocker Bugs verification
* Docker Compose testing for eSignet and signup (windows, Linux and Mac)

=== Feature Health

=== Test execution statistics

=== Functional test results

Below are the test metrics by performing functional testing using mock
MDS, mock Auth and mock ABIS. The process followed was black box testing
which based its test cases on the specifications of the software
component under test. The functional tests were performed in combination
of individual module testing as well as integration testing. Test data
were prepared in line with the user stories. Expected results were
monitored by examining the user interface. The coverage includes GUI
testing, System testing, End-To-End flows across multiple languages and
configurations. The testing cycle included simulation of multiple
identity schema and respective UI schema configurations.

Total

Passed

Failed

Skipped

3183

3110

38

35

Test Rate: 98% with Pass rate: 98%

Here is the detailed breakdown:

Test cases

Total

API Based Testing - eSignet

2017

Passed

1962

Failed

20

Skipped

35

UI Based Testing

1166

Passed

1148

Failed

18

Skipped

0

API Testrig results for eSignet and Signup with Mock ID:

Test cases

Total

API Based Testrig - eSignet

Total

1011

Passed

93

Failed

0

Skipped

0

Ignored

918

API Based Testrig - eSignet-signup

585

Passed

559

Failed

0

Skipped

0

Ignored

26

API Testrig results for eSignet and Signup with MOSIP ID:

Test cases

Total

API Based Testrig - eSignet

1011

Passed

842

Failed

0

Skipped

0

Ignored

169

API Based Testrig - eSignet-signup

585

Passed

301

Failed

1

Skipped

0

Ignored

283

API Testrig results for eSignet and Signup with Sunbird:

Test cases

Total

API Based Testrig - Sunbird

1011

Passed

93

Failed

0

Skipped

0

Ignored

918

++{++% hint style="`warning`" %} *Note*: In API Based testing, 35 test
cases are marked as skipped as they were not automated and cannot be
tested using postman. ++{++% endhint %}

===== Detailed Test metrics:

Below are the detailed test metrics by performing manual/automation
testing. The project metrics are derived from Defect density, Test
coverage, Test execution coverage, test tracking, and efficiency.

The various metrics that assist in test tracking and efficiency are as
follows:

* Passed Test Cases Coverage: It measures the percentage of passed test
cases. (Number of passed tests / Total number of tests executed) x 100
* Failed Test Case Coverage: It measures the percentage of all failed
test cases. (Number of failed tests / Total number of test cases
executed) x 100

===== Sonar Report:

Repo Name

Branch Name

Release Version (POM)

Coverage (++>++80%)

Reliability (0)

Security (0)

Hotspots (0)

Duplications(Less than 3%)

eSigent

release-1.6.x

release-1.6.1

86.2

0

0

0

0%

eSignet Signup

release-1.2.x

release-1.2.1

79.3

0

0

0

0%

esignet-mock-services

release-0.11.x

release-0.11.1

83.3

0

0

0

0%

esignet-plugins(mock-plugin)

release-1.3.x

release-1.3.2

83.0

0

0

0

2.9%

esignet-plugins(mosip-identity-plugin)

release-1.3.2

release-1.3.2

83.6

0

0

0

0%

esignet-plugins(sunbird-rc-plugin)

release-1.3.2

release-1.3.2

83

0

0

0

0%

'''''
