== Integration with eSignet portal

The integration of the SignUp module with eSignet is provisioned. To
enable this integration, configure the following properties in eSignet
according to your requirements:

[arabic]
. *Display Signup Option on Authentication Screen*: Ensure that the
option for SignUp is visible to the user when they land on the
authentication screen. This can be configured by adjusting the relevant
display settings or UI properties within the eSignet configuration.

SignUp Option on Authentication Screen

Below property should be marked as true, if the signup banner should be
displayed. If not required, a banner can be hidden by setting the flag
to false. By default, the signup banner is enabled as shown below:

[source,javascript]
----
mosip.esignet.ui.signup.config = 
{
  'signup.banner': true,
  'signup.url': '${mosip.signup.domain.url}/signup'
};
----

[arabic, start=2]
. *Configuring Forgot Password*: For password-based authentication, the
"`Forgot Password`" link is enabled by default on the authentication
screen. To disable this link, set the corresponding flag to *false* in
the configuration as shown below:

[source,javascript]
----
mosip.esignet.ui.forgot-password.config = 
{
  'forgot-password': true,
  'forgot-password.url': '${mosip.signup.domain.url}/reset-password'
};
----

Forgot Password Page

[arabic, start=3]
. *Consent for Unavailable Claims:* For the Identity (eKYC) verification
process, eSignet includes a built-in feature to inform the user when
certain verified claims are unavailable. A popup is displayed, showing
details of the missing claims and prompting the user to initiate the
verification process. Detailed consent regarding the Personally
Identifiable Information (PII) that will be captured during the
verification will be handled through the SignUp portal.

Claim Details Page
